# -*- coding: utf-8 -*-
"""tweepy_walkthrough

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159AZ_7z1A8tGkzrFa2S6-_8uVjNxhMsy

# **1: Testing Twitter API**
"""

API_Key         = "replace_me"
API_Secret      = "replace_me"
Bearer_Token    = "replace_me"
Access_Token    = "replace_me"
Access_Secret   = "replace_me"

"""### Get recent public tweets on keywords"""

!pip install tweepy==4.9.0
import tweepy

# Authenticate with Twitter OAuth 2.0 Bearer Token (Application-only)
client = tweepy.Client(Bearer_Token)

# Pull tweets from twitter

query = '#chatgpt -is:retweet lang:en'
tweets = client.search_recent_tweets(query=query, tweet_fields=['context_annotations', 'created_at'], max_results=10)

# Get tweets that contain the hashtag #TypeKeywordHere
# -is:retweet means I don't want retweets
# lang:en is asking for the tweets to be in english

for tweet in tweets.data:
    print('\n**Tweet Text**\n',tweet.text)

"""# **2: Tweepy**

## Tweepy - API Class (Twitter API v1.1)

### Set up environment
"""

# !pip install tweepy==4.9.0
# import tweepy

"""### Authentication"""

# Authenticate with Twitter OAuth 1.0a User Context
auth = tweepy.OAuth1UserHandler(

   API_Key,                     # API / Consumer Key here
   API_Secret,                  # API / Consumer Secret here
   Access_Token,                # Access Token here
   Access_Secret                # Access Token Secret here
)
api = tweepy.API(auth)

"""### Make a tweet

"""

tweet = api.update_status("Hey there!! Courtesy: Tweepy v3")

"""### Get tweets from home timeline"""

# Get recent tweets from your home timeline
tweets = api.home_timeline(count=5)
for tweet in tweets:
    print(tweet.text,'\n')

"""### Get your own tweets"""

# Get Tweets (recent tweets from your account)
tweets = api.user_timeline(count=2)
for tweet in tweets:
    print(tweet.text,'\n')

# Tweet object has lots of data. Let's check out the Tweet JSON specs
tweets = api.user_timeline(count=2)
for tweet in tweets:
    print(tweet.created_at)
    print(tweet.id_str)
    print(tweet.text,'\n')

"""### Delete a tweet"""

# Delete a Tweet
to_be_deleted_tweet = api.update_status('Bad Tweet')

api.destroy_status(to_be_deleted_tweet.id_str)

"""### Follow someone"""

# Follow
api.create_friendship(screen_name='@YouTube')

# Unfollow
api.destroy_friendship(screen_name='@YouTube')

"""## Tweepy - Client Class (Twitter API v2.0)

### Authentication
"""

# !pip install tweepy==4.9.0
# import tweepy

# Authenticate with Twitter OAuth 2.0 Bearer Token (Application-only)
client = tweepy.Client(Bearer_Token)

# Pull tweets from twitter

query = '#chatgpt -is:retweet lang:en'
tweets = client.search_recent_tweets(query=query, tweet_fields=['context_annotations', 'created_at'], max_results=10)

# Get tweets that contain the hashtag #TypeKeywordHere
# -is:retweet means I don't want retweets
# lang:en is asking for the tweets to be in english

for tweet in tweets.data:
    print('\n**Tweet Text**\n',tweet.text)